#!/bin/bash
# runs different deploys based on flags
# s for server, d for client dev, p for client prod
# valid options are s, sp, sd, d

# Initialize variables to 0
s_flag=0
d_flag=0
p_flag=0

# Parse command line options
while getopts "sdp" opt; do
  case $opt in
    s) s_flag=1 ;;
    d) d_flag=1 ;;
    p) p_flag=1 ;;
    \?) exit 1
    ;;
  esac
done

if [ $d_flag -eq 1 ] && [ $p_flag -eq 1 ]
then
  echo "Can't build client prod and dev at the same time. Try running with -d or -p flag."
  exit 1
fi

if [ $s_flag -eq 1 ]
then
  if [ $d_flag -eq 1 ]
  then
    docker-compose -f dockerstuff/docker-compose-serverclientdev.yaml -t server-clientdev up --build
  elif [ $p_flag -eq 1 ]
  then
    docker run --build -f dockerstuff/server-clientprod.dockerfile -t server-clientprod .
  else
    docker run --build -f dockerstuff/server.dockerfile -t server .
  fi
else
  if [ $d_flag -eq 1 ]
  then
    docker run --build -f dockerstuff/clientdev.dockerfile -t clientdev .
  else
    echo "Can't build client prod without server build. Try running with -s flag."
    exit 1
  fi
fi