#!/bin/sh

case $1 in
  s)
    npm run dev --prefix server
    ;;
  d)
    npm start --prefix client
    ;;
  sd)
    npm run dev --prefix server & npm start --prefix client
    ;;
  sp)
    npm run build --prefix client & npm start --prefix server 
    ;;
esac